apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
        image: webapp-image
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "rootpass"
        - name: DB_NAME
          value: "webappdb"
        ports:
        - containerPort: 80
